# Generated by Django 5.1.1 on 2024-11-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_manufacturer_product_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
