# Generated by Django 5.1.1 on 2024-11-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_manufacturer_remove_product_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
