# Generated by Django 5.1.1 on 2024-11-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('preparation', 'En preparacion'), ('shipping', 'En camino'), ('delivered', 'Entregado')], default='preparation', max_length=20),
        ),
    ]
