# Generated by Django 5.1.1 on 2024-11-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
